// flow-typed signature: 45f1e19198b556412577d1efadd472c6
// flow-typed version: <<STUB>>/semantic-ui-offline_v^2.2.1-3.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-ui-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-ui-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-ui-offline/bin/recreate' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/accordion' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/accordion.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/api' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/api.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/checkbox' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/checkbox.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/colorize' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/colorize.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/dimmer' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/dimmer.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/dropdown' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/dropdown.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/embed' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/embed.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/form' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/form.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/modal' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/modal.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/nag' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/nag.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/popup' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/popup.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/progress' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/progress.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/rating' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/rating.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/search' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/search.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/shape' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/shape.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/sidebar' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/sidebar.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/site' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/site.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/state' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/state.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/sticky' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/sticky.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/tab' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/tab.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/transition' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/transition.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/video' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/video.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/visibility' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/visibility.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/visit' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/components/visit.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/package' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/semantic' {
  declare module.exports: any;
}

declare module 'semantic-ui-offline/semantic.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-ui-offline/bin/recreate.js' {
  declare module.exports: $Exports<'semantic-ui-offline/bin/recreate'>;
}
declare module 'semantic-ui-offline/components/accordion.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/accordion'>;
}
declare module 'semantic-ui-offline/components/accordion.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/accordion.min'>;
}
declare module 'semantic-ui-offline/components/api.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/api'>;
}
declare module 'semantic-ui-offline/components/api.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/api.min'>;
}
declare module 'semantic-ui-offline/components/checkbox.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/checkbox'>;
}
declare module 'semantic-ui-offline/components/checkbox.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/checkbox.min'>;
}
declare module 'semantic-ui-offline/components/colorize.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/colorize'>;
}
declare module 'semantic-ui-offline/components/colorize.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/colorize.min'>;
}
declare module 'semantic-ui-offline/components/dimmer.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/dimmer'>;
}
declare module 'semantic-ui-offline/components/dimmer.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/dimmer.min'>;
}
declare module 'semantic-ui-offline/components/dropdown.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/dropdown'>;
}
declare module 'semantic-ui-offline/components/dropdown.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/dropdown.min'>;
}
declare module 'semantic-ui-offline/components/embed.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/embed'>;
}
declare module 'semantic-ui-offline/components/embed.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/embed.min'>;
}
declare module 'semantic-ui-offline/components/form.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/form'>;
}
declare module 'semantic-ui-offline/components/form.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/form.min'>;
}
declare module 'semantic-ui-offline/components/modal.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/modal'>;
}
declare module 'semantic-ui-offline/components/modal.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/modal.min'>;
}
declare module 'semantic-ui-offline/components/nag.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/nag'>;
}
declare module 'semantic-ui-offline/components/nag.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/nag.min'>;
}
declare module 'semantic-ui-offline/components/popup.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/popup'>;
}
declare module 'semantic-ui-offline/components/popup.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/popup.min'>;
}
declare module 'semantic-ui-offline/components/progress.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/progress'>;
}
declare module 'semantic-ui-offline/components/progress.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/progress.min'>;
}
declare module 'semantic-ui-offline/components/rating.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/rating'>;
}
declare module 'semantic-ui-offline/components/rating.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/rating.min'>;
}
declare module 'semantic-ui-offline/components/search.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/search'>;
}
declare module 'semantic-ui-offline/components/search.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/search.min'>;
}
declare module 'semantic-ui-offline/components/shape.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/shape'>;
}
declare module 'semantic-ui-offline/components/shape.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/shape.min'>;
}
declare module 'semantic-ui-offline/components/sidebar.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/sidebar'>;
}
declare module 'semantic-ui-offline/components/sidebar.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/sidebar.min'>;
}
declare module 'semantic-ui-offline/components/site.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/site'>;
}
declare module 'semantic-ui-offline/components/site.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/site.min'>;
}
declare module 'semantic-ui-offline/components/state.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/state'>;
}
declare module 'semantic-ui-offline/components/state.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/state.min'>;
}
declare module 'semantic-ui-offline/components/sticky.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/sticky'>;
}
declare module 'semantic-ui-offline/components/sticky.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/sticky.min'>;
}
declare module 'semantic-ui-offline/components/tab.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/tab'>;
}
declare module 'semantic-ui-offline/components/tab.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/tab.min'>;
}
declare module 'semantic-ui-offline/components/transition.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/transition'>;
}
declare module 'semantic-ui-offline/components/transition.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/transition.min'>;
}
declare module 'semantic-ui-offline/components/video.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/video'>;
}
declare module 'semantic-ui-offline/components/video.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/video.min'>;
}
declare module 'semantic-ui-offline/components/visibility.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/visibility'>;
}
declare module 'semantic-ui-offline/components/visibility.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/visibility.min'>;
}
declare module 'semantic-ui-offline/components/visit.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/visit'>;
}
declare module 'semantic-ui-offline/components/visit.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/components/visit.min'>;
}
declare module 'semantic-ui-offline/package.js' {
  declare module.exports: $Exports<'semantic-ui-offline/package'>;
}
declare module 'semantic-ui-offline/semantic.js' {
  declare module.exports: $Exports<'semantic-ui-offline/semantic'>;
}
declare module 'semantic-ui-offline/semantic.min.js' {
  declare module.exports: $Exports<'semantic-ui-offline/semantic.min'>;
}
